server.port=8090
spring.application.name=gateway-service

# Новый префикс для webflux gateway в 2025.x
spring.cloud.gateway.server.webflux.routes[0].id=notes-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://NOTES-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/notes/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=AddRequestHeader=X-Gateway, true

spring.cloud.gateway.server.webflux.routes[1].id=ping-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://NOTES-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/ping
spring.cloud.gateway.server.webflux.routes[1].filters[0]=AddRequestHeader=X-Gateway, true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.lease-renewal-interval-in-seconds=5

management.endpoints.web.exposure.include=health,gateway
management.endpoint.gateway.enabled=true